### PR TITLE
Adding the CPGs graphic

### PR DESCRIPTION
**Pull request by ghost**
This graphic is provided for inclusion in the header of the README file (main page)

#  #

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

### CODE REVIEW

**Review by felddy — APPROVED** [review]
That's quite a large graphic.
Were you going to update the README as well in this PR?

**Comment by ghost** [comment]
> That's quite a large graphic. Were you going to update the README as well in this PR?

Yes, I would like the README updated if possible, so this will appear underneath the headline. My contacts through CISAGraphics weren't sure what size to make the file. They use 1200x628 (FB/Lin); 1024x512 (Twitter), and 1080x1080 (IG) exported to 150ppi for social. I wasn't sure what was standard here, so I requested the same size as Facebook and LinkedIn.

Do we need something different?

**Comment by dav3r** [comment]
> > That's quite a large graphic. Were you going to update the README as well in this PR?
> 
> Yes, I would like the README updated if possible, so this will appear underneath the headline. My contacts through CISAGraphics weren't sure what size to make the file. They use 1200x628 (FB/Lin); 1024x512 (Twitter), and 1080x1080 (IG) exported to 150ppi for social. I wasn't sure what was standard here, so I requested the same size as Facebook and LinkedIn.
> 
> Do we need something different?

I think what @felddy was getting at is that you should update this pull request to include the change(s) to your README where you actually use this new graphic, rather than creating a separate PR to add the graphic to the README.

**Comment by ghost** [comment]
> > > That's quite a large graphic. Were you going to update the README as well in this PR?
> > 
> > 
> > Yes, I would like the README updated if possible, so this will appear underneath the headline. My contacts through CISAGraphics weren't sure what size to make the file. They use 1200x628 (FB/Lin); 1024x512 (Twitter), and 1080x1080 (IG) exported to 150ppi for social. I wasn't sure what was standard here, so I requested the same size as Facebook and LinkedIn.
> > Do we need something different?
> 
> I think what @felddy was getting at is that you should update this pull request to include the change(s) to your README where you actually use this new graphic, rather than creating a separate PR to add the graphic to the README.

Thanks @dav3r. Can you contact me over Teams? I don't know how to include it there without uploading it to the repository first.

**Comment by ghost** [comment]
Closing this PR in favor of #7 with help from @dav3r.

**Pull request closed without merging**
